### ISSUE TITLE
consideration for the messenger page far balancing wire vs telegram

### ISSUE THREAD

**Issue by iteco** [danarel/thinkprivacy#14]
Few comments for the check marks on messenger page
(https://www.thinkprivacy.io/messengers.html)

* Telegram has transparency reports here: https://t.me/transparency
* Telegram messages are encrypted by default. (Not end-to-end, but still strongly encrypted)
   more in 
    https://telegram.org/faq#q-so-how-do-you-encrypt-data
    https://telegram.org/faq#q-do-you-process-data-requests 

* Telegram client is open source. Get it from F-Droid (https://f-droid.org/en/packages/org.telegram.messenger/). Server is not open source, but Wire's servers are not either.. however, other has a check mark, but other don't.

Wire is not available in F-Droid. See more
https://gitlab.com/fdroid/rfp/issues/108
https://github.com/wireapp/wire-android/issues/233
So by downloading default Wireapp you get 3rd party trackers built-in. Perhaps you should add one row to the comparison table bring this up? 

Has wire really 'Refused to cooperate with government agencies?', or should there be a gray question mark too ?

The big guy behind the wire project is Janus Friis that was co-founder of Kazaa and Skype (https://en.wikipedia.org/wiki/Wire_(software)), and Skype had a backdoor and Kazaa was delivering Malware (https://en.wikipedia.org/wiki/Kazaa). Few audits don't convince me before the server is fully open source too.. which doesn't seem to go forward.. (https://github.com/wireapp/wire/issues/160)  Vaporware/Promisware ?

**Comment by danarel** [comment]
Thank you for the feedback, and I want to address some of your concerns here:

> Telegram has transparency reports here: https://t.me/transparency

I can't view or see that they offer any reports unless I sign up for their service and install their app. If they are going to make their reports private, I will continue to say they don't offer such reports. I am not able to verify they have a single report in this group. 

> Telegram messages are encrypted by default. (Not end-to-end, but still strongly encrypted)
> more in
> https://telegram.org/faq#q-so-how-do-you-encrypt-data
> https://telegram.org/faq#q-do-you-process-data-requests

Please read about their encryption offerings here: https://securechatguide.org/centralizedapps.html#telegram

Long story shot, it's not very secure and they don't offer E2EE by default. 

> Telegram client is open source. Get it from F-Droid (https://f-droid.org/en/packages/org.telegram.messenger/). Server is not open source, but Wire's servers are not either.. however, other has a check mark, but other don't.

Actually, the Wire source code for their server is here: https://github.com/wireapp/wire-server and you can learn more about that here: https://medium.com/@wireapp/open-sourcing-wire-server-code-ef7866a731d5

> Wire is not available in F-Droid. See more
> https://gitlab.com/fdroid/rfp/issues/108
> wireapp/wire-android#233
> So by downloading default Wireapp you get 3rd party trackers built-in. Perhaps you should add one row to the comparison table bring this up?

I would love to see Wire on F-Droid, but for the same reasons Signal isn't on there, it's hard to fault them for it. I would prefer we move people off Android devices than pretend like just because it's on F-Droid it's suddenly super secure. Also, like Signal, Android users can download the APK directly. 

Wire also uses zero android app trackers: https://securechatguide.org/centralizedapps.html#wire

> Has wire really 'Refused to cooperate with government agencies?', or should there be a gray question mark too ?

Because Wire has a public transparency report, you're able to verify this, unlike with Telegram. 

https://wire-docs.wire.com/download/Wire+Transparency+Report.pdf

They follow Swiss law carefully and won't hand over anything if not done through proper channels.

In 2018 they denied 2 of the 3 requests sent in.

In 2018, they had 1 request that was legally processed by the Swiss gov't, but thanks to Wire's encryption, they are only able to give the gov't basic user information, that information is noted clearly on the chart.

> The big guy behind the wire project is Janus Friis that was co-founder of Kazaa and Skype (https://en.wikipedia.org/wiki/Wire_(software)), and Skype had a backdoor and Kazaa was delivering Malware (https://en.wikipedia.org/wiki/Kazaa). Few audits don't convince me before the server is fully open source too.. which doesn't seem to go forward.. (wireapp/wire#160) Vaporware/Promisware ?

This is all baseless nonsense. Friis sold Skype in 2005, yes he founded it, but it's now owned by a surveillance capitalist which of course would allow a backdoor. Friis isn't part of that company though. 

If you're not going to trust audits, then I don't know what to tell you. You're hear defending Telegram, an app that openly works with government agencies and isn't open about their "transparency" reports, but don't trust the one company that is.

With that, nothing you've added seems to change the outcome of the chart. Telegram is not recommended and is not for all intents and purposes a very secure messaging app.

**Comment by iteco** [comment]
> Thank you for the feedback, and I want to address some of your concerns here:

Thank you for the answers. Few comments back below.

> > Telegram has transparency reports here: https://t.me/transparency
> 
> I can't view or see that they offer any reports unless I sign up for their service and install their app. If they are going to make their reports private, I will continue to say they don't offer such reports. I am not able to verify they have a single report in this group.

Well.. their app is free to use and if you can read it from there, I think that it is not fair to say that it is private, and not to consider it at all. However, I checked that channel now, and I didn't see any reports although they said to release those semiannual somewhere at the end of 2018. I guess one should be out already.. so you are right here. At least until one comes out. :-)

> 
> > Telegram messages are encrypted by default. (Not end-to-end, but still strongly encrypted)
> > more in
> > https://telegram.org/faq#q-so-how-do-you-encrypt-data
> > https://telegram.org/faq#q-do-you-process-data-requests
> 
> Please read about their encryption offerings here: https://securechatguide.org/centralizedapps.html#telegram
> 

Checked.

> Long story shot, it's not very secure and they don't offer E2EE by default.

All true, but seems that their encryption is still good enough, even by default.

> > Telegram client is open source. Get it from F-Droid (https://f-droid.org/en/packages/org.telegram.messenger/). Server is not open source, but Wire's servers are not either.. however, other has a check mark, but other don't.
> 
> Actually, the Wire source code for their server is here: https://github.com/wireapp/wire-server and you can learn more about that here: https://medium.com/@wireapp/open-sourcing-wire-server-code-ef7866a731d5

However, we don't know if they run that server version in the public instance. You will also make a reference to that medium post where they are promising federation, but that has not gone forward after that as the github issue is pointing.

> > Wire is not available in F-Droid. See more
> > https://gitlab.com/fdroid/rfp/issues/108
> > [wireapp/wire-android#233](https://github.com/wireapp/wire-android/issues/233)
> > So by downloading default Wireapp you get 3rd party trackers built-in. Perhaps you should add one row to the comparison table bring this up?
> 
> I would love to see Wire on F-Droid, but for the same reasons Signal isn't on there, it's hard to fault them for it.

Why? I would not take much time from them to do it.

> I would prefer we move people off Android devices than pretend like just because it's on F-Droid it's suddenly super secure. Also, like Signal, Android users can download the APK directly.
> 
> Wire also uses zero android app trackers: https://securechatguide.org/centralizedapps.html#wire

Hmm.. Strange. How F-Droid (https://gitlab.com/fdroid/rfp/issues/108) is seeing that they have those ? 


> > Has wire really 'Refused to cooperate with government agencies?', or should there be a gray question mark too ?
> 
> Because Wire has a public transparency report, you're able to verify this, unlike with Telegram.
> https://wire-docs.wire.com/download/Wire+Transparency+Report.pdf
> 
> They follow Swiss law carefully and won't hand over anything if not done through proper channels.

Ah. So complying for Government's lawful request is counted as resisting.. :)
As Telegram had that same check mark, I thougt that it was something bigger as e.g. what Telegram had done with Russians. 

> > The big guy behind the wire project is Janus Friis that was co-founder of Kazaa and Skype (https://en.wikipedia.org/wiki/Wire_(software)), and Skype had a backdoor and Kazaa was delivering Malware (https://en.wikipedia.org/wiki/Kazaa). Few audits don't convince me before the server is fully open source too.. which doesn't seem to go forward.. ([wireapp/wire#160](https://github.com/wireapp/wire/issues/160)) Vaporware/Promisware ?
> 
> This is all baseless nonsense. Friis sold Skype in 2005, yes he founded it, but it's now owned by a surveillance capitalist which of course would allow a backdoor. Friis isn't part of that company though.

Backdoor to Skype was revealed after Friis left from the Skype, but it is not know that when the backdoor was done. However, you don't address the Kazaa case at all. Any comments for that ?  
 
> If you're not going to trust audits, then I don't know what to tell you. You're hear defending Telegram, an app that openly works with government agencies

Can you give some references for that ?
 
> and isn't open about their "transparency" reports, but don't trust the one company that is.
> 
> With that, nothing you've added seems to change the outcome of the chart. Telegram is not recommended and is not for all intents and purposes a very secure messaging app.

It is no way perfect, but I don't see it so much below the wire. (btw. I have them both, but prefer Telegram as it works (perhaps it is only me), but I don't get any notifications from Wire)
