### ISSUE TITLE
Please stop using CloudFlare.

### ISSUE THREAD

**Issue by ghost** [danarel/thinkprivacy#5]
> we're aiming to deliver the best information available for a better privacy

If your statement is true, please don't use CloudFlare.
Your website's visitor(not me)'s toot: https://masto.nixnet.xyz/@amolith/101588202702599511

---

[Problem with CloudFlare](https://github.com/privacytoolsIO/privacytools.io/issues/374#issuecomment-460077544)
[General problem with Cloudflare's MITM attack on the Internet](https://trac.torproject.org/projects/tor/ticket/24351)
[What you can do to resist Cloudflare?](https://notabug.org/themusicgod1/cloudflare-tor/src/master/what-to-do.md)

**Comment by danarel** [comment]
ThinkPrivacy no longer uses Cloudflare.

**Comment by Amolith** [comment]
I think the point of this issue was simply that Cloudflare shouldn't be a recommendation on your site for DNS, not that the site itself used Cloudflare (though it's certainly good that you've removed that). Looking at the link in my toot again, I see that Cloudflare is still among the DNS recommendations as well as listed first.

If you don't want to remove it entirely, maybe move it to the bottom? You could also add [UncensoredDNS](https://blog.uncensoreddns.org/). I use them as the secondary DNS on my servers as well as laptop with [Unbound](https://nlnetlabs.nl/projects/unbound/about/) as my primary though I do think that's a *bit* too technical for who ThinkPrivacy is targeting lol.

**Comment by danarel** [comment]
@Amolith 

Noted, and it's been removed (reflected in the newest push) and will be on the live site the next time I upload. I will check out your recommendations as well.
